### ISSUE TITLE
Add 5 Custom Instructions

### ISSUE THREAD

**Issue by Creastoff** [KristofIsSleepy/InstructionDrawing#8]
Create 5 custom instructions such as drawing a rectangle.

> You should aim to add at least five new Instructions in order to fulfill this requirement. Use your imagination a little, as more impressive Instructions are likely to attract more marks.

**Comment by Creastoff** [comment]
Added:

- Dashed Line Here: https://github.com/KristofIsSleepy/InstructionDrawing/commit/f7258135384e50f2e44a21e1747e6527b9ca83de

Remaining Instructions To Add:

- Rectangle (Clear) (width, height)
- Rectangle (Filled) (width, height)
- Spiral (width, height, gap, size )
- Tetris-L Block (side, width, height)
- Oval (horizontalRadius, verticalRadius)
- Triangle (width, height)

**Comment by KristofIsSleepy** [comment]
Add Drawing Functionality For The Following:

- Rectangle (Clear) (width & height)
- Rectangle (Filled) (width & height)
- Spiral (LineGap)
- Tetris-L Block (side, width, height)
- Oval (horizontalRadius, verticalRadius)
- Triangle (width, height)

**Comment by Creastoff** [comment]
Added:

- Rectangle (Clear) Here: https://github.com/KristofIsSleepy/InstructionDrawing/commit/1211ebd315bbae491c30ff34eb1eccca9a73e7db
- Rectangle (Filled) Here: https://github.com/KristofIsSleepy/InstructionDrawing/commit/1211ebd315bbae491c30ff34eb1eccca9a73e7db
- Spiral (LineGap) Here: https://github.com/KristofIsSleepy/InstructionDrawing/commit/1211ebd315bbae491c30ff34eb1eccca9a73e7db

Remaining Instructions To Add:

- Tetris-L Block (side, width, height)
- Oval (horizontalRadius, verticalRadius)
- Triangle (width, height)

**Comment by Creastoff** [comment]
Added:

- Oval (Clear) Here: https://github.com/KristofIsSleepy/InstructionDrawing/commit/0b96bba3569903b166c5745d1f0b1a9f78df2442

- Oval (Filled) Here: https://github.com/KristofIsSleepy/InstructionDrawing/commit/0b96bba3569903b166c5745d1f0b1a9f78df2442

Remaining Instructions To Add:

- Tetris-L Block (side, width, height)
- Triangle (width, height)

**Comment by Creastoff** [comment]
Added:

- Isosceles Triangle (Clear) Here: https://github.com/KristofIsSleepy/InstructionDrawing/commit/e17da4dea441bbc4621c65f57a3851a3f1fd5ce0
- Isosceles Triangle (Filled) Here: https://github.com/KristofIsSleepy/InstructionDrawing/commit/e17da4dea441bbc4621c65f57a3851a3f1fd5ce0
- Tetris-L Block Here: https://github.com/KristofIsSleepy/InstructionDrawing/commit/0d843da2dd5dcd4743f73d339a796c7bd31df62b
